#!/usr/bin/env bash
#
# Builds the Rust static library for Apple platforms and packages it as the
# xcframeworks consumed by the Swift Package Manager manifests in
# rust_builder/ios and rust_builder/macos.
#
# Swift Package Manager cannot build the Rust code itself: its build tool
# plugins run sandboxed without network access, which cargo requires. The
# CocoaPods path still builds from source via cargokit and is unaffected by
# this script.
#
# Usage:
#   ./scripts/build_rust_xcframework.sh [--debug] [--ios-only | --macos-only]
#
set -euo pipefail

PROFILE="release"
CARGO_FLAGS=("--release")
PLATFORM="all"
for arg in "$@"; do
  case "$arg" in
    --debug)
      PROFILE="debug"
      CARGO_FLAGS=()
      ;;
    --ios-only)
      PLATFORM="ios"
      ;;
    --macos-only)
      PLATFORM="macos"
      ;;
    *)
      echo "error: unknown option $arg" >&2
      exit 1
      ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUST_DIR="$REPO_ROOT/rust"
LIB_NAME="rust_lib_magicepaperapp"
STATIC_LIB="lib${LIB_NAME}.a"
BUILD_DIR="$REPO_ROOT/build/rust_xcframework"

IOS_TARGETS=(aarch64-apple-ios)
IOS_SIM_TARGETS=(aarch64-apple-ios-sim x86_64-apple-ios)
MACOS_TARGETS=(aarch64-apple-darwin x86_64-apple-darwin)

command -v cargo >/dev/null || { echo "error: cargo not found on PATH" >&2; exit 1; }
if ! xcodebuild -version >/dev/null 2>&1; then
  echo "error: xcodebuild requires a full Xcode install (Command Line Tools alone are not enough)" >&2
  exit 1
fi

echo "==> Ensuring Rust targets are installed"
if [[ "$PLATFORM" != "macos" ]]; then
  rustup target add "${IOS_TARGETS[@]}" "${IOS_SIM_TARGETS[@]}"
fi
if [[ "$PLATFORM" != "ios" ]]; then
  rustup target add "${MACOS_TARGETS[@]}"
fi

build_targets() {
  for target in "$@"; do
    echo "==> Building $target ($PROFILE)"
    (cd "$RUST_DIR" && cargo build "${CARGO_FLAGS[@]}" --target "$target")
  done
}

# Combines the per-architecture static libraries for one platform into a single
# fat archive, which is what xcframework slices expect.
lipo_slice() {
  local slice_name="$1"
  shift
  local out_dir="$BUILD_DIR/$slice_name"
  mkdir -p "$out_dir"
  local inputs=()
  for target in "$@"; do
    inputs+=("$RUST_DIR/target/$target/$PROFILE/$STATIC_LIB")
  done
  lipo -create "${inputs[@]}" -output "$out_dir/$STATIC_LIB"
  echo "$out_dir/$STATIC_LIB"
}

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

if [[ "$PLATFORM" != "macos" ]]; then
  build_targets "${IOS_TARGETS[@]}" "${IOS_SIM_TARGETS[@]}"
  IOS_LIB="$(lipo_slice ios-device "${IOS_TARGETS[@]}")"
  IOS_SIM_LIB="$(lipo_slice ios-simulator "${IOS_SIM_TARGETS[@]}")"
fi
if [[ "$PLATFORM" != "ios" ]]; then
  build_targets "${MACOS_TARGETS[@]}"
  MACOS_LIB="$(lipo_slice macos "${MACOS_TARGETS[@]}")"
fi

# Headers are generated by flutter_rust_bridge into the Dart side only; the
# xcframework ships the archive alone, matching what the podspec force-loads.
IOS_XCFRAMEWORK="$REPO_ROOT/rust_builder/ios/$LIB_NAME/$LIB_NAME.xcframework"
MACOS_XCFRAMEWORK="$REPO_ROOT/rust_builder/macos/$LIB_NAME/$LIB_NAME.xcframework"

if [[ "$PLATFORM" != "macos" ]]; then
  rm -rf "$IOS_XCFRAMEWORK"
  echo "==> Creating iOS xcframework"
  xcodebuild -create-xcframework \
    -library "$IOS_LIB" \
    -library "$IOS_SIM_LIB" \
    -output "$IOS_XCFRAMEWORK"
fi

if [[ "$PLATFORM" != "ios" ]]; then
  rm -rf "$MACOS_XCFRAMEWORK"
  echo "==> Creating macOS xcframework"
  xcodebuild -create-xcframework \
    -library "$MACOS_LIB" \
    -output "$MACOS_XCFRAMEWORK"
fi

echo
echo "Done."
if [[ "$PLATFORM" != "macos" ]]; then
  echo "  $IOS_XCFRAMEWORK"
fi
if [[ "$PLATFORM" != "ios" ]]; then
  echo "  $MACOS_XCFRAMEWORK"
fi
