// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `closest_color`, `distribute_error`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Colorf32`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<Uint8List> processImageRust(
        {required List<int> imageBytes,
        required int targetWidth,
        required int targetHeight,
        required DitherMethod method,
        required bool isBwr}) =>
    RustLib.instance.api.crateApiSimpleProcessImageRust(
        imageBytes: imageBytes,
        targetWidth: targetWidth,
        targetHeight: targetHeight,
        method: method,
        isBwr: isBwr);

enum DitherMethod {
  floydSteinberg,
  falseFloydSteinberg,
  stucki,
  atkinson,
  threshold,
  halftone,
  ;
}
